apiVersion: v1
kind: ConfigMap
metadata:
  name: live-location-frontend-configmap
  labels:
    app: live-location-frontend-configmap
data:
  PORT: "5011"
  REACT_APP_SOCKET_URL: "http://live-location-service:80/"
  REACT_APP_API_URL: "http://live-location-service:80/"
  NODE_ENV: "development"
  # REACT_APP_IDENTITY_SERVER_URL: "123"
