apiVersion: v1
kind: ConfigMap
metadata:
  name: live-location-frontend-configmap
  labels:
    app: live-location-frontend-configmap
data:
  PORT: "3000"
  # Update these URLs to use the new Ingress address
  REACT_APP_SOCKET_URL: "http://k8s-default-liveloca-cf415ea493-1188327969.us-east-1.elb.amazonaws.com/"
  REACT_APP_API_URL: "http://k8s-default-liveloca-cf415ea493-1188327969.us-east-1.elb.amazonaws.com/api"
  NODE_ENV: "development"
  # REACT_APP_IDENTITY_SERVER_URL: "123"

